### ISSUE TITLE
inv_imu_adv_enable_clkin_rtc don't work?

### ISSUE THREAD

**Issue by litesky** [tdk-invn-oss/motion.mcu.icm45686.driver#3]
Hi

i want use mpu's pin9 (int2) as clkin. but after call the function (inv_imu_adv_enable_clkin_rtc), the mpu stop work.
the clk's freq is 32kHz, both rise time and fall time are 20ns.

SIFS_I3C_STC_CFG from ~~0x23~~ to **0x23**
IPREG_SYS2_REG_123 from ~~0x34~~ to **0x36** (the reset value on datasheet is 0x14, but the value i got is 0x34)
IPREG_SYS1_REG_166 from ~~0x1B~~ to **0x5B**
RTC_CONFIG from ~~0x03~~ to **0x23**

additional,
SMC_CONTROL_0 from ~~0x60~~ to **0x70**

**Comment by tdk-opensource** [comment]
Thank you for opening this issue! We will look into it shortly.<br><br>Notifying @tdk-invn-oss/motion-maintainers

**Comment by litesky** [comment]
hi
ICM42688 has register PIN9_FUNCTION, for set Pin9 as CLKIN input.

Is ICM45686 make Pin9 as CLKIN input automatically, after call function (inv_imu_adv_enable_clkin_rtc) ?

**Comment by lmichallon-invn** [comment]
Hi @litesky,

With the ICM-45686, the pin9 can be configured either for INT2, FSYNC or CLKIN functions. To select CLKIN, you have to set the PADS_INT2_CFG_OVRD_VAL to 2. 

Within our driver, this configuration is done through the `inv_imu_adv_set_int2_pin_usage` function. Only then, you can call the `inv_imu_adv_enable_clkin_rtc` function.

The application code would result in something like:
```C
rc |= inv_imu_adv_set_int2_pin_usage(&imu_dev, IOC_PAD_SCENARIO_OVRD_INT2_CFG_OVRD_VAL_CLKIN);
rc |= inv_imu_adv_enable_clkin_rtc(&imu_dev);
```

I hope it helps. Let me know otherwise.

Best Regards,
Loic

**Comment by litesky** [comment]
hi, Loic.
thank you so much for your help.

the mpu (ICM45686) work well now, with rtc clkin.
